sul-dlss/rialto-derivatives

lambda/README.md

The ordered list markup wasn't working, just doing it manually.

Fix formatting on README

---

lambda/.solr_wrapper.yml
lambda/Gopkg.lock
lambda/README.md
lambda/main.go
lambda/main_test.go
lambda/solr_config/_rest_managed.json
lambda/solr_config/admin-extra.html
lambda/solr_config/elevate.xml
lambda/solr_config/mapping-ISOLatin1Accent.txt
lambda/solr_config/protwords.txt
lambda/solr_config/schema.xml
lambda/solr_config/scripts.conf
lambda/solr_config/solrconfig.xml
lambda/solr_config/spellings.txt
lambda/solr_config/stopwords.txt
lambda/solr_config/stopwords_en.txt
lambda/solr_config/synonyms.txt
lambda/solr_config/xslt/example.xsl
lambda/solr_config/xslt/example_atom.xsl
lambda/solr_config/xslt/example_rss.xsl
lambda/solr_config/xslt/luke.xsl

Let's talk about what direction to go in before we merge this.  This is a hedge against the possibility that we can't get Blacklight to work on Elasticsearch.

Write to solr (rather than Elasticsearch)

---

lambda/Makefile
lambda/README.md

Adds a makefile to build, upload, and subscribe the lambda.

Add makefile to build

---

.circleci/config.yml
actions/rebuild.go
actions/touch.go
actions/touch_test.go
main.go
main_test.go
transform/indexer.go
transform/indexer_test.go

Rename to rialto-derivatives to match GitHub repository name

---

models/predicates.go
models/resource.go
models/resource_test.go
transform/composite_indexer.go
transform/organization_indexer.go
transform/organization_indexer_test.go

Add an organization indexer

---

models/predicates.go
models/resource.go
models/resource_test.go
transform/composite_indexer.go
transform/grant_indexer.go
transform/grant_indexer_test.go

Add a grant indexer

---

models/predicates.go
models/resource.go
transform/composite_indexer.go
transform/person_indexer_test.go
transform/project_indexer.go
transform/project_indexer_test.go

Add a project indexer

---

repository/sparql_reader.go

Increase the timeout from 1.5 to 10s

---

main.go
runtime/registry.go
transform/composite_indexer.go
transform/composite_indexer_test.go
transform/person_indexer.go

This enables it to look up Name resources for the given person.
Fixes #42

Pass a handle to the SPARQL service to the person indexer

---

transform/composite_indexer.go
transform/type_indexer.go
transform/type_indexer_test.go

Index the more specific type of Agent

---

models/predicates.go

For compatibility with sample data.

Use the http://www.w3.org/2004/02/skos/core namespace

---

models/predicates.go

This reverts commit d7fc98ab1fc1f1e14a79887664b2c89c0baafbfc.

Revert "Use the http://www.w3.org/2004/02/skos/core namespace"

---

actions/rebuild.go
actions/rebuild_test.go
derivative/postgres_client_test.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer_test.go

Rather than trying to load them all into memory.
Fixes #54

Iterate over all the triples in batches

---

models/person.go
models/publication.go
models/publication_test.go
repository/sparql_reader.go
transform/organization_indexer.go
transform/publication_indexer.go

Allow publication subtype to be optional

---

.circleci/config.yml

Quick fix to the duplicate command causing an error in circle.

Remove duplicate unnecessary commands

---

models/predicates.go
models/resource.go
models/resource_test.go
repository/sparql_reader.go
transform/concept_indexer_test.go

This is the namespace even for the 2008 version: https://www.w3.org/TR/skos-reference/#namespace-documents

Use the http://www.w3.org/2004/02/skos/core# namespace

---

repository/sparql_reader.go

Fixes https://github.com/sul-dlss-labs/rialto-derivatives/issues/72

Increase timeout to 60s

---

repository/service.go

NewResource always returns pointers to the Person object

Cast to a person pointer rather than a person

---

actions/touch.go
actions/touch_test.go
derivative/postgres_client_test.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer_test.go

Support multiple subjects per message

---

repository/sparql_reader.go

Don't abort when encountering an unregistered type

---

repository/service.go
repository/sparql_reader.go

Prevent empty results from causing a null pointer error

---

models/publication.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer_test.go
transform/publication_indexer.go
transform/publication_indexer_test.go

Index authors on publications

---

models/publication.go
models/publication_test.go
models/resource_test.go
repository/sparql_reader.go
transform/composite_indexer_test.go
transform/publication_indexer.go
transform/publication_indexer_test.go

Map more publication fields to solr

---

derivative/postgres_client.go

Panics on SQL errors.

---

Gopkg.lock
Makefile
cmd/postgres/main.go
repository/sparql_reader.go

Adds triple store retrying. Adds local lambda deployment to make file.

---

repository/sparql_reader.go

None of the authors coming from Web of Science have more specific types

Person subtype is optional

---

README.md
derivative/postgres_client.go
derivative/postgres_client_test.go

Handle dupe keys by adding ON CONFLICT to insert.

---

models/person.go
models/person_test.go

Fixes NPE in person.

---

derivative/postgres_client.go
derivative/postgres_client_test.go
repository/sparql_reader.go
transform/publication_serializer.go
transform/publication_serializer_test.go

Adds publications serializer.

---

models/publication.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer_test.go
transform/publication_indexer.go
transform/publication_indexer_test.go

refs https://github.com/sul-dlss-labs/rialto-webapp/issues/96

Adds concepts to publication solr docs.

---

models/organization.go
repository/sparql_reader.go

Includes orgs without subtypes.

---

models/person.go
models/person_test.go
repository/sparql_reader.go

Adds non-Stanford orgs to person's solr doc.

---

derivative/postgres_client_test.go
models/person.go
models/person_test.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer_test.go
transform/person_serializer.go
transform/person_serializer_test.go

Adds countries for person.

---

database.dump
derivative/postgres_client.go
derivative/postgres_client_test.go

Switches to using URIs for joining publications and people.

---

database.dump
derivative/postgres_client.go
derivative/postgres_client_test.go
models/organization.go
models/person.go
models/publication.go
transform/organization_serializer.go
transform/organization_serializer_test.go
transform/person_indexer.go
transform/person_serializer.go
transform/person_serializer_test.go
transform/publication_serializer.go
transform/publication_serializer_test.go

Ref sul-dlss-labs/rialto-derivatives#109

Use the name column for organizations and people

---

derivative/postgres_client_test.go
models/person.go
models/person_test.go
repository/sparql_reader.go
transform/person_indexer.go
transform/person_serializer.go
transform/person_serializer_test.go

refs https://github.com/sul-dlss-labs/rialto-webapp/issues/108

Adds country for person postgres and solr.

---

models/person.go
models/person_test.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer.go
transform/person_indexer_test.go

refs sul-dlss-labs/rialto-webapp#113

Switches to RIALTO person subtypes and adds to person solr index.

---

derivative/postgres_client_test.go
models/person.go
models/person_test.go
transform/person_indexer.go
transform/person_serializer.go
transform/person_serializer_test.go

Adds institutes for postgres and solr.

---

derivative/postgres_client_test.go
models/publication.go
models/publication_test.go
transform/publication_indexer.go
transform/publication_indexer_test.go
transform/publication_serializer.go
transform/publication_serializer_test.go

Adds created year to publication postgres and solr.

---

models/grant.go
models/grant_test.go
models/labeled.go
models/person.go
models/publication.go
models/resource_test.go
repository/sparql_reader.go
transform/grant_indexer.go
transform/grant_indexer_test.go

ref sul-dlss-labs/rialto-webapp#133
ref #129

Index the grant PI

---

models/publication.go
models/publication_test.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer_test.go
transform/publication_indexer.go
transform/publication_indexer_test.go

Index grants on publications

---

.circleci/config.yml

Sorry - quick follow up to #146 - we need the full path here.

Circle needs full path

---

models/publication.go
repository/sparql_reader.go

Also updated authors so all 1-N joins use the same fields.

Use the correct fields for indexing grants

---

models/publication.go
models/publication_test.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer_test.go
transform/publication_indexer.go
transform/publication_indexer_test.go

Changes identifier to zero or more for publications.

---

models/grant.go
models/grant_test.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/grant_indexer.go
transform/grant_indexer_test.go
transform/person_indexer_test.go
transform/publication_indexer.go

Indexes start date, end date, and identifiers for grants.

---

README.md

Update the readme for multiple lambdas

---

README.md

Update SNS message example.

---

README.md

Update handler names

---

README.md

Borrowed this approach from https://github.com/localstack/awscli-local/blob/master/bin/awslocal#L98-L100
Fixes #98

Document environment variables needed for localstack.

---

derivative/postgres_client.go
derivative/postgres_client_test.go
models/publication.go
models/publication_test.go
repository/reader.go
repository/service.go
repository/sparql_reader.go
transform/person_indexer_test.go
transform/publication_serializer.go
transform/publication_serializer_test.go

Add limiting publications by created year and Stanford authors.
